### ISSUE TITLE
takes multiple runs to save all groups?

### ISSUE THREAD

**Issue by YesThatAllen** [vindia/discourse_user_importer#3]
I used this script to import ~80 users in up to 4 groups each.

it seemed to me that I needed to run this many times before each user had all their groups. 

Is that a known issue?

(running it multiple times  was simple and caused no errors, so it was a minor hassle, once I realized they weren't all in all the right groups)

**Comment by vindia** [comment]
That's not a known issue and it's not expected behaviour either. What the script does is either of the following, given the following CSV-file (some columns left out for simplicity's sake):

```
email;groups
foo@example.com;bat
```

### 1. Existing user

If a User exists, it will check if there are any new groups defined for this user and add them to the existing User

**Example**: User `foo@example.com` exists, and belongs to the groups `bar` and `baz` already. After running the script User `foo@example.com` will be updated and belong to the groups `bar`, `baz`, and `bat`.

### 2. No existing user

If no User exists, it will add the User with all the defined groups.

**Example**: User `foo@example.com` does not exist yet. After running the script User `foo@example.com` will be created an belong to the group `bat`.

---

So, to be honest, if I scan the script quickly, I can't think of a reason why you would need to run the script multiple times to add all the groups. But then again, bugs can be subtle. Can you give me a (simplified) example of where it went wrong for you?
